[target.x86_64-unknown-linux-musl]
linker = "rust-lld"

[target.aarch64-unknown-linux-musl]
linker = "rust-lld"

[env]
PATH = { value = "C:\\Users\\Nicolas\\Documents\\augment-projects\\udp-to-tcp\\llvm-mingw-20240619-ucrt-x86_64\\bin;%PATH%", force = true }
